### ISSUE TITLE
no datasets

### ISSUE THREAD

**Issue by jdy160012** [InnovArul/rgb_IR_personreid#2]
I'm very interested in your paper and I feel it's very innovative.I want to reproduce it. But  data set link can't be opened.

**Comment by InnovArul** [comment]
Hi, It is not my paper. I have just reproduced the results by independently implementing it. The paper is from  Mr.Ancong Wu (https://github.com/wuancong).

The dataset link is working: https://www.dropbox.com/sh/v036mg1q4yg7awb/AABhxU-FJ4X2oyq7-Ts6bgD0a?dl=0

**Comment by jdy160012** [comment]
Thank you very  much.

**Comment by jdy160012** [comment]
Hi， I  have not reproduced the result .Can I  ask  for your help  in the process of  production?

**Comment by InnovArul** [comment]
You can take the source code in the current repository, as a reference when you are implementing, I guess. If you have further questions, please pose here.

**Comment by jdy160012** [comment]
thank  you发自我的华为手机-------- 原始邮件 --------主题：Re: [InnovArul/rgb_IR_personreid] no datasets (#2)发件人：Arulkumar 收件人：InnovArul/rgb_IR_personreid 抄送：jdy160012 <15635623558@163.com>,Author You can take the source code in the current repository, as a reference when you are implementing, I guess. If you have further questions, please pose here.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/InnovArul/rgb_IR_personreid/issues/2?email_source=notifications\u0026email_token=ANGQCQI5SLQ6IJDHRLEZTO3QKHWAFA5CNFSM4IXL3NP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD67MILQ#issuecomment-532595758",
"url": "https://github.com/InnovArul/rgb_IR_personreid/issues/2?email_source=notifications\u0026email_token=ANGQCQI5SLQ6IJDHRLEZTO3QKHWAFA5CNFSM4IXL3NP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD67MILQ#issuecomment-532595758",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by InnovArul** [comment]
closing the issue, as it is resolved. Please open a new one if needed.

**Comment by jdy160012** [comment]
thank  you
