### ISSUE TITLE
some questions during the reproducing

### ISSUE THREAD

**Issue by jdy160012** [InnovArul/rgb_IR_personreid#3]
Excuse me , there is a error -----The NVIDIA driver on your system is too old (found version 9000).  Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx  Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version  of the CUDA driver during my
reproducing.
      But  I  use the CPU-tensorflow , what should I do?

**Comment by InnovArul** [comment]
Hi,

The code in this repository is written using pytorch (with GPU usage).

**Comment by jdy160012** [comment]
Thank you

**Comment by jdy160012** [comment]
Have I to use GPU-tensorflow?

**Comment by InnovArul** [comment]
This repository contains code written using pytorch (a similar framework for deep learning like TensorFlow). You can find more details about pytorch here: https://pytorch.org/get-started/locally/.

You can rewrite the codebase in tensorflow (using tensorflow components), of course, if you want.

**Comment by jdy160012** [comment]
thank you

**Comment by InnovArul** [comment]
I am closing the issue for now. Please feel free to reopen an issue if you have questions.
