### ISSUE TITLE
What's your project's running environment? 

### ISSUE THREAD

**Issue by zhaoqiguo** [InnovArul/rgb_IR_personreid#4]
Could you please give the exact version of each libraries used in this project?

**Comment by InnovArul** [comment]
I am not sure about the exact environment that I used when creating this project. Nevertheless, I am able to execute the code in the conda environment exported here: https://github.com/InnovArul/rgb_IR_personreid/blob/master/conda_env.yml

Hope it helps!

**Comment by InnovArul** [comment]
Closing the issue. Feel free to re-open if you have questions.
